# 应用名称
spring:
  application:
    name: consume

#  rabbitmq:
#    host: localhost
#    port: 5672
#    virtual-host: /
#    username: guest
#    password: guest
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    # 开启手动确认：在收到消息处理完业务后再调用 channel.basicAck() 确认消。否则将再收到消息后自动确认，业务可能会处理失败造成数据丢失
    listener:
      simple:
        acknowledge-mode: manual
  redis:
    # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
    database: 3
    # redis服务器地址（默认为loaclhost）
    host: localhost
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password:
    # redis连接超时时间（单位毫秒）
    timeout: 0
    # redis连接池配置
    pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 8
      # 最大空闲连接数（默认为8，负数表示无限）
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）

redis:
  key:
    ttl: 60
